apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
 name: vm1 
 namespace: kbench-vm-namespace
spec:
 className: best-effort-small
 #TODO: imageName should be dynamic
 imageName: vmi-eb9dea97ecad960e8
 powerState: poweredOn
 storageClass: wcp-policy